"""Initial migration

Revision ID: d659050b5ca8
Revises: 
Create Date: 2026-06-12 13:21:40.632576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd659050b5ca8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feasibility_reports', 'conversation_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('feasibility_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feasibility_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('feasibility_reports', 'conversation_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
